apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3  # Number of pod replicas to maintain
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: 331717872891.dkr.ecr.us-east-1.amazonaws.com/githubworkflownode:latest  # Docker image to use for the pods
        ports:
        - containerPort: 3000  # Port to expose on the container
