name: ci-cd learning

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          # role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
          aws-region: aws-region-1
      -
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
      - 
        name: Build Docker image
        run: docker build -t githubworkflownode:latest . 
      - 
        name: Tag Docker image
        run: docker tag 331717872891.dkr.ecr.us-east-1.amazonaws.com/githubworkflownode:latest

      - name: Push Docker image to ECR
        run: docker push 331717872891.dkr.ecr.us-east-1.amazonaws.com/githubworkflownode:latest
