name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
      -
        name: Login on ec2
        uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      -
        name: Pull Docker Image on EC2
        run: |
             echo "$SSH_PRIVATE_KEY" > ssh_key.pem
             chmod 600 ssh_key.pem
             ssh -i ssh_key.pem ubuntu@ec2-44-204-23-43.compute-1.amazonaws.com  'docker pull chouhanviky9/clockbox:latest'
        
      -
        name: Start Docker Container on EC2
        run: |
             echo "$SSH_PRIVATE_KEY" > ssh_key.pem
             chmod 600 ssh_key.pem
             ssh -i ssh_key.pem ubuntu@ec2-44-204-23-43.compute-1.amazonaws.com 'docker run -d -p 3000:3000 chouhanviky9/clockbox:latest'
              