name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          region: us-east-1
      - 
        name: Build Docker image
        run: docker build -t githubworkflownode:latest . 
      - 
        name: Tag Docker image
        run: docker tag 331717872891.dkr.ecr.us-east-1.amazonaws.com/githubworkflownode:latest

      - name: Push Docker image to ECR
        run: docker push 331717872891.dkr.ecr.us-east-1.amazonaws.com/githubworkflownode:latest
